import { Ubuntu } from "next/font/google";


import "./globals.css";
import AuthProvider from "@/provider/AuthProvider";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/lib/Providers";
import Headers from "@/components/Header";


const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-ubuntu",
});



export const metadata = {
  title: "Booking System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} font-sans antialiased`}>
        <Toaster position="top-center" reverseOrder={false} />
        <Providers>
          <AuthProvider>
            <Headers/>
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
